apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-deployment
  labels:
    app: color-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: anil1318/color-api:1.1.0
          ports:
            - containerPort: 80
