apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: anil1318/traffic-gen:1.0.0
    args:
      - 'my-external-service'
      - '0.5'
