apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: color-api-ss
spec:
  selector:
    matchLabels:
      app: color-api
  serviceName: color-svc
  replicas: 5
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
      - name: color-api
        image: anil1318/color-api:1.2.1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: dummy-data
          mountPath: /tmp/data
  volumeClaimTemplates:
  - metadata:
      name: dummy-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hostpath
      resources:
        requests:
          storage: 1Gi
