apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
  - name: myapp
    image: anil1318/alpine-curl:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"