apiVersion: v1
kind: Pod
metadata:
  name: green-color-api
  labels:
    app: green-color-api
spec:
  containers:
    - name: color-api
      image: anil1318/color-api:1.3.0
      envFrom:
        - configMapRef:
            name: green-env-vars
      # env:
      #   - name: COLOR_CONFIG_PATH
      #     valueFrom:
      #       configMapKeyRef:
      #         key: COLOR_CONFIG_PATH
      #         name: green-config
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: color-config
          mountPath: /mnt/config
  volumes:
    - name: color-config
      configMap:
        name: green-files
      
