apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  namespace: dev
  labels:
    app: heavy-api
spec:
  containers:
  - name: heavy-api
    image: anil1318/color-api:1.1.0
    resources:
      requests:
        cpu: '4'
        memory: '4Gi'
      limits:
        cpu: '8'
        memory: '12Gi'
    ports:
      - containerPort: 80
