apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: prod
  name: prod-quota
spec:
  hard:
    requests.cpu: '4'
    requests.memory: '4Gi'
    limits.cpu: '8'
    limits.memory: '16Gi'
