apiVersion: v1
kind: PersistentVolume
metadata:
  name: ss-0
spec:
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/Users/celia/OneDrive/Desktop/Anil/k8/ss-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ['docker-desktop']
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ss-1
spec:
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/Users/celia/OneDrive/Desktop/Anil/k8/ss-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ['docker-desktop']
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ss-2
spec:
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/Users/celia/OneDrive/Desktop/Anil/k8/ss-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ['docker-desktop']