apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: busy-box
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.36.1
          command:
            - 'sh'
            - '-c'
            - 'sleep 3600'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          volumeMounts:
            - name: local-volume
              mountPath: /mnt/local
  volumeClaimTemplates:
    - metadata:
        name: local-volume
      spec:
        resources:
          requests:
            storage: 128Mi
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage