apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: prod
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: anil1318/color-api:1.1.0
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  namespace: prod
  labels:
    aoo: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
  - port: 80
    targetPort: 80
