apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-api
      environment: local
      tier: backend
    matchExpressions:
      - key: managed
        operator: Exists
  template:
    metadata:
      labels:
        app: color-api
        environment: local
        tier: backend
        release: stable
        managed: 'true'
    spec:
      containers:
      - name: color-api
        image: anil1318/color-api:1.1.0
        ports:
        - containerPort: 80
